---
- name: Run show commands on all switches and print the output
  hosts: all
  vars:
    ansible_connection: httpapi
    ansible_network_os: eos
    ansible_user: admin
    ansible_password: admin
    ansible_become: yes
    ansible_become_method: enable
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
  tasks:
  - name: run show commands
    arista.eos.eos_command:
      commands:
      - command: show ip bgp summary
        output: text
    register: cli_output
  - name: display result
    debug:
      var: cli_output.stdout
