---
- name: Run show commands on all switches and print the output
  hosts: all
  vars:
    ansible_connection: httpapi
    ansible_network_os: eos
    ansible_user: admin
    ansible_password: admin
    ansible_become: yes
    ansible_become_method: enable
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
  tasks:
  - name: run show commands
    arista.eos.eos_command:
      commands:
      - show ip bgp summary
      - show port-channel dense
      - show lldp neighbors
    register: cli_output
  - name: display result
    ansible.builtin.debug:
      msg:
      - "show ip bgp summary"
      - "{{ cli_output.stdout_lines[0] }}"
      # - "{% for line in cli_output.stdout_lines[0] %}{{ line }}{% endfor %}"
      - "show port-channel dense"
      - "{% for line in cli_output.stdout_lines[1] %}{{ line }}{% endfor %}"
      - "show lldp neighbors"
      - "{% for line in cli_output.stdout_lines[2] %}{{ line }}{% endfor %}"
      
